<?php
/**
 * @file This file exists solely to document groups and stuff.
 */

/**
 * 
 * @defgroup events Events
 * Various event keys that can be trapped.
 * @see EventManagerInterface
 * 
 * @defgroup config Configuration Settings
 * Various configuration settings that can be modified.
 * @see ConfigurationManagerInterface
 * 
 * @defgroup args Arguments
 * Various arguments that can be modified
 * @see ArgsInterface
 * 
 * @defgroup plugins Plugins
 * Plugins extend the functionality of the system in different ways.
 * 
 * @defgroup commands Commands
 * Commands provide additional options for the system.
 * 
 * @defgroup debug_levels Debug Levels
 * Different debug levels that are available to output handlers.
 * 
 * @defgroup log_levels Log Levels
 * Different levels of log messages.
 * 
 * @defgroup message_types Message Types
 * Different message types.
 * 
 */